import type { ProductTypeConfig } from "@/types";

/**
 * 彩印纸盒产品类型配置
 * 新增产品类型只需在此目录添加新配置文件并在 registry 中注册
 */
export const colorPrintBoxConfig: ProductTypeConfig = {
  code: "color_print_box",
  name: "彩印纸盒",
  description: "彩色印刷纸盒/彩盒，适用于消费品包装、礼品盒等场景",
  steps: [
    {
      id: "upload",
      title: "上传资料",
      description: "上传设计图纸和产品参考照片，帮助系统更准确识别产品特征",
    },
    {
      id: "info",
      title: "补充信息",
      description: "填写订单与产品关键参数，信息越完整，估算越准确",
      fieldKeys: [
        "quantity",
        "length",
        "width",
        "height",
        "boxType",
        "material",
        "grammage",
        "fluteType",
        "printMethod",
        "colorCount",
        "spotColorCount",
        "surfaceTreatment",
        "needGluing",
        "provideReadyDesign",
        "deliveryLocation",
        "targetDelivery",
        "specialRequirements",
      ],
    },
    {
      id: "report",
      title: "成本报告",
      description: "查看多维度成本拆解与优化建议",
    },
  ],
  fields: [
    {
      key: "quantity",
      label: "订单数量",
      type: "number",
      required: true,
      weight: 15,
      impactHint: "数量直接影响材料采购单价与开机成本分摊",
      placeholder: "如：10000",
      unit: "个",
      group: "订单信息",
    },
    {
      key: "length",
      label: "长度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "尺寸决定用纸面积与排版效率",
      placeholder: "mm",
      unit: "mm",
      group: "产品尺寸",
    },
    {
      key: "width",
      label: "宽度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "尺寸决定用纸面积与排版效率",
      placeholder: "mm",
      unit: "mm",
      group: "产品尺寸",
    },
    {
      key: "height",
      label: "高度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "尺寸决定用纸面积与排版效率",
      placeholder: "mm",
      unit: "mm",
      group: "产品尺寸",
    },
    {
      key: "boxType",
      label: "盒型结构",
      type: "select",
      required: false,
      weight: 8,
      impactHint: "盒型影响用纸利用率与人工/设备工时（天地盖、开窗盒更复杂）",
      group: "产品尺寸",
      options: [
        { value: "tuck_end", label: "标准扣底盒 (×1.0)" },
        { value: "rigid_cover", label: "天地盖精品盒 (×1.35)" },
        { value: "special_window", label: "异形/开窗盒 (×1.25)" },
      ],
      defaultValue: "tuck_end",
    },
    {
      key: "material",
      label: "材质",
      type: "select",
      required: true,
      weight: 12,
      impactHint: "材质是材料成本的核心决定因素",
      group: "材料规格",
      options: [
        { value: "white_card", label: "白卡纸" },
        { value: "coated_paper", label: "铜版纸" },
        { value: "grey_board", label: "灰底白板" },
        { value: "kraft", label: "牛皮纸" },
        { value: "special", label: "特种纸" },
      ],
    },
    {
      key: "grammage",
      label: "克重",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "克重影响材料单价与盒体挺度",
      group: "材料规格",
      options: [
        { value: "250", label: "250g" },
        { value: "300", label: "300g" },
        { value: "350", label: "350g" },
        { value: "400", label: "400g" },
        { value: "450", label: "450g" },
      ],
    },
    {
      key: "fluteType",
      label: "裱坑坑型（瓦楞彩盒）",
      type: "select",
      required: false,
      weight: 6,
      impactHint: "白卡+坑纸的瓦楞彩盒将额外计算坑纸/底纸与裱坑加工费",
      group: "材料规格",
      options: [
        { value: "none", label: "无（非瓦楞）" },
        { value: "E_flute", label: "E坑" },
        { value: "B_flute", label: "B坑" },
      ],
      defaultValue: "none",
    },
    {
      key: "printMethod",
      label: "印刷方式",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "印刷方式影响制版费与单位印刷成本",
      group: "印刷工艺",
      options: [
        { value: "offset", label: "胶印" },
        { value: "digital", label: "数码印刷" },
        { value: "flexo", label: "柔印" },
      ],
    },
    {
      key: "colorCount",
      label: "CMYK 印刷色数",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "CMYK 色数影响油墨成本与印刷难度（专色请另填专色色数）",
      group: "印刷工艺",
      options: [
        { value: "1", label: "单色" },
        { value: "2", label: "双色" },
        { value: "3", label: "三色" },
        { value: "4", label: "四色 (CMYK)" },
      ],
    },
    {
      key: "spotColorCount",
      label: "专色色数 (Spot Color)",
      type: "number",
      required: false,
      weight: 4,
      impactHint: "专色需额外调色/洗车费与专色版费，显著影响成本",
      placeholder: "如：1",
      unit: "色",
      group: "印刷工艺",
      defaultValue: 0,
    },
    {
      key: "surfaceTreatment",
      label: "表面处理",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "表面处理工艺影响加工成本",
      group: "印刷工艺",
      options: [
        { value: "none", label: "无" },
        { value: "matte_laminate", label: "哑膜" },
        { value: "gloss_laminate", label: "亮膜" },
        { value: "uv", label: "UV上光" },
        { value: "foil", label: "烫金/烫银" },
        { value: "emboss", label: "压纹/击凸" },
      ],
    },
    {
      key: "needGluing",
      label: "是否糊盒",
      type: "boolean",
      required: true,
      weight: 8,
      impactHint: "糊盒增加人工成本",
      group: "后道工艺",
      defaultValue: true,
    },
    {
      key: "provideReadyDesign",
      label: "是否已提供完稿文件",
      type: "boolean",
      required: false,
      weight: 3,
      impactHint: "客户已提供可印刷完稿时，设计费减免为0",
      group: "后道工艺",
      defaultValue: false,
    },
    {
      key: "deliveryLocation",
      label: "交付地点",
      type: "select",
      required: true,
      weight: 9,
      impactHint: "交付地点影响物流与包装成本，并决定人工地域系数",
      group: "交付信息",
      options: [
        { value: "east_china", label: "华东" },
        { value: "south_china", label: "华南" },
        { value: "north_china", label: "华北" },
        { value: "central_china", label: "华中" },
        { value: "southwest", label: "西南" },
        { value: "northeast", label: "东北" },
      ],
    },
    {
      key: "targetDelivery",
      label: "目标交期",
      type: "select",
      required: false,
      weight: 4,
      impactHint: "紧急交期可能产生加急费用",
      group: "交付信息",
      options: [
        { value: "standard", label: "标准 (15-20天)" },
        { value: "urgent", label: "加急 (7-10天)" },
        { value: "express", label: "特急 (3-5天)" },
      ],
      defaultValue: "standard",
    },
    {
      key: "specialRequirements",
      label: "特殊要求",
      type: "text",
      required: false,
      weight: 3,
      impactHint: "特殊工艺可能显著影响成本",
      placeholder: "如：内托、开窗、磁吸等",
      group: "其他",
    },
  ],
  dimensions: [
    {
      key: "material",
      label: "材料成本",
      group: "manufacturing",
      expectedRatioRange: [35, 55],
      agentId: "material_agent",
      description: "纸张/板材采购成本，含损耗",
      order: 1,
    },
    {
      key: "labor",
      label: "人工成本",
      group: "manufacturing",
      expectedRatioRange: [5, 18],
      agentId: "labor_agent",
      description: "手工操作、糊盒等人工工序，随生产地域浮动",
      order: 2,
    },
    {
      key: "process",
      label: "加工费（含设备）",
      group: "manufacturing",
      expectedRatioRange: [12, 30],
      agentId: "process_agent",
      description: "印刷、覆膜、烫金、模切等设备及油墨驱动工艺",
      order: 3,
    },
    {
      key: "design_plate",
      label: "设计与制版成本",
      group: "commercial",
      expectedRatioRange: [3, 40],
      agentId: "design_agent",
      description: "设计费、CTP制版、打样等",
      order: 5,
    },
    {
      key: "finance_other",
      label: "财务与其他成本",
      group: "commercial",
      expectedRatioRange: [5, 15],
      agentId: "finance_agent",
      description: "管理费用、物流、包装、税费、利润等",
      order: 6,
    },
  ],
};
