import type { ProductTypeConfig } from "@/types";

/**
 * 瓦楞纸箱产品类型配置
 * 材料为多层复合纸板（挂面纸 + 芯纸 + 中纸），成本按层分别计；
 * 人工/工艺/设计/财务复用彩盒（color_print_box）同维度 Agent 分支，
 * 仅材料 Agent 走专属 corrugatedMaterialAgent（见 specialists.ts）。
 */
export const corrugatedBoxConfig: ProductTypeConfig = {
  code: "corrugated_box",
  name: "瓦楞纸箱",
  description: "瓦楞纸箱/运输箱（单瓦/双瓦/三瓦），按面纸·芯纸·里纸分层核算纸板成本",
  steps: [
    {
      id: "upload",
      title: "上传资料",
      description: "上传设计图纸和产品参考照片，帮助系统更准确识别产品特征",
    },
    {
      id: "info",
      title: "补充信息",
      description: "填写订单与产品关键参数，信息越完整，估算越准确",
      fieldKeys: [
        "quantity",
        "length",
        "width",
        "height",
        "boxType",
        "boardStructure",
        "fluteType",
        "linerMaterial",
        "linerGrammage",
        "fluteGrammage",
        "mediumGrammage",
        "printMethod",
        "colorCount",
        "spotColorCount",
        "surfaceTreatment",
        "needGluing",
        "provideReadyDesign",
        "deliveryLocation",
        "targetDelivery",
        "specialRequirements",
      ],
    },
    {
      id: "report",
      title: "成本报告",
      description: "查看多维度成本拆解与优化建议",
    },
  ],
  fields: [
    {
      key: "quantity",
      label: "订单数量",
      type: "number",
      required: true,
      weight: 15,
      impactHint: "数量直接影响材料采购单价与开机成本分摊",
      placeholder: "如：5000",
      unit: "只",
      group: "订单信息",
    },
    {
      key: "length",
      label: "长度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "尺寸决定用纸面积与排版效率",
      placeholder: "mm",
      unit: "mm",
      group: "产品尺寸",
    },
    {
      key: "width",
      label: "宽度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "尺寸决定用纸面积与排版效率",
      placeholder: "mm",
      unit: "mm",
      group: "产品尺寸",
    },
    {
      key: "height",
      label: "高度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "尺寸决定用纸面积与排版效率",
      placeholder: "mm",
      unit: "mm",
      group: "产品尺寸",
    },
    {
      key: "boxType",
      label: "箱型结构",
      type: "select",
      required: false,
      weight: 8,
      impactHint: "箱型影响用纸利用率与人工/模切工时",
      group: "产品尺寸",
      options: [
        { value: "rsc", label: "常规开槽箱 (RSC)" },
        { value: "die_cut", label: "模切箱" },
        { value: "folder", label: "折叠箱 (Folder)" },
      ],
      defaultValue: "rsc",
    },
    {
      key: "boardStructure",
      label: "纸板结构（层数）",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "单瓦3层/双瓦5层/三瓦7层，决定挂面纸与芯纸层数",
      group: "材料规格",
      options: [
        { value: "single", label: "单瓦（3层）" },
        { value: "double", label: "双瓦（5层）" },
        { value: "triple", label: "三瓦（7层）" },
      ],
      defaultValue: "single",
    },
    {
      key: "fluteType",
      label: "坑型",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "坑型决定芯纸展开系数(take-up)与芯纸层数；双坑组合适用于双瓦",
      group: "材料规格",
      options: [
        { value: "A", label: "A坑" },
        { value: "B", label: "B坑" },
        { value: "C", label: "C坑" },
        { value: "E", label: "E坑" },
        { value: "F", label: "F坑" },
        { value: "BC", label: "BC双坑" },
        { value: "BE", label: "BE双坑" },
        { value: "AB", label: "AB双坑" },
      ],
      defaultValue: "B",
    },
    {
      key: "linerMaterial",
      label: "面纸/里纸材质（挂面纸）",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "挂面纸材质是材料成本核心，牛皮/白板价格不同",
      group: "材料规格",
      options: [
        { value: "kraft", label: "牛皮挂面纸" },
        { value: "white_top", label: "白板/白牛皮" },
        { value: "special", label: "特种纸" },
      ],
      defaultValue: "kraft",
    },
    {
      key: "linerGrammage",
      label: "面纸/里纸克重",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "挂面纸克重影响纸板定量与挺度",
      group: "材料规格",
      options: [
        { value: "125", label: "125g" },
        { value: "150", label: "150g" },
        { value: "175", label: "175g" },
        { value: "200", label: "200g" },
        { value: "230", label: "230g" },
        { value: "250", label: "250g" },
      ],
      defaultValue: "175",
    },
    {
      key: "fluteGrammage",
      label: "芯纸克重",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "芯纸（瓦楞中纸）克重，压型后按 take-up 系数放大耗纸",
      group: "材料规格",
      options: [
        { value: "90", label: "90g" },
        { value: "100", label: "100g" },
        { value: "110", label: "110g" },
        { value: "120", label: "120g" },
        { value: "140", label: "140g" },
        { value: "160", label: "160g" },
        { value: "180", label: "180g" },
      ],
      defaultValue: "120",
    },
    {
      key: "mediumGrammage",
      label: "中纸克重（双/三瓦）",
      type: "select",
      required: false,
      weight: 8,
      impactHint: "双瓦/三瓦的中间挂面层克重；单瓦无需填写",
      group: "材料规格",
      showWhen: { field: "boardStructure", value: ["double", "triple"] },
      options: [
        { value: "110", label: "110g" },
        { value: "120", label: "120g" },
        { value: "140", label: "140g" },
        { value: "160", label: "160g" },
      ],
      defaultValue: "120",
    },
    {
      key: "printMethod",
      label: "印刷方式",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "瓦楞纸箱多为柔印(flexo)，预印彩箱可用胶印",
      group: "印刷工艺",
      options: [
        { value: "flexo", label: "柔印" },
        { value: "offset", label: "胶印（预印）" },
        { value: "digital", label: "数码印刷" },
      ],
      defaultValue: "flexo",
    },
    {
      key: "colorCount",
      label: "CMYK 印刷色数",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "CMYK 色数影响油墨与制版成本",
      group: "印刷工艺",
      options: [
        { value: "1", label: "单色" },
        { value: "2", label: "双色" },
        { value: "3", label: "三色" },
        { value: "4", label: "四色 (CMYK)" },
      ],
      defaultValue: "4",
    },
    {
      key: "spotColorCount",
      label: "专色色数 (Spot Color)",
      type: "number",
      required: false,
      weight: 4,
      impactHint: "专色需额外调色/洗车费与专色版费",
      placeholder: "如：1",
      unit: "色",
      group: "印刷工艺",
      defaultValue: 0,
    },
    {
      key: "surfaceTreatment",
      label: "表面处理",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "运输箱多无处理；预印彩箱可覆膜/上光",
      group: "印刷工艺",
      options: [
        { value: "none", label: "无" },
        { value: "matte_laminate", label: "哑膜" },
        { value: "gloss_laminate", label: "亮膜" },
        { value: "uv", label: "UV上光" },
      ],
      defaultValue: "none",
    },
    {
      key: "needGluing",
      label: "是否粘箱/成型",
      type: "boolean",
      required: true,
      weight: 8,
      impactHint: "粘箱/钉箱增加人工成本；折叠箱(RSC/Folder)可免",
      group: "后道工艺",
      defaultValue: true,
    },
    {
      key: "provideReadyDesign",
      label: "是否已提供完稿文件",
      type: "boolean",
      required: false,
      weight: 3,
      impactHint: "客户已提供可印刷完稿时，设计费减免为0",
      group: "后道工艺",
      defaultValue: false,
    },
    {
      key: "deliveryLocation",
      label: "交付地点",
      type: "select",
      required: true,
      weight: 9,
      impactHint: "交付地点影响物流与包装成本，并决定人工地域系数",
      group: "交付信息",
      options: [
        { value: "east_china", label: "华东" },
        { value: "south_china", label: "华南" },
        { value: "north_china", label: "华北" },
        { value: "central_china", label: "华中" },
        { value: "southwest", label: "西南" },
        { value: "northeast", label: "东北" },
      ],
    },
    {
      key: "targetDelivery",
      label: "目标交期",
      type: "select",
      required: false,
      weight: 4,
      impactHint: "紧急交期可能产生加急费用",
      group: "交付信息",
      options: [
        { value: "standard", label: "标准 (15-20天)" },
        { value: "urgent", label: "加急 (7-10天)" },
        { value: "express", label: "特急 (3-5天)" },
      ],
      defaultValue: "standard",
    },
    {
      key: "specialRequirements",
      label: "特殊要求",
      type: "text",
      required: false,
      weight: 3,
      impactHint: "特殊工艺可能显著影响成本",
      placeholder: "如：加强钉、防水处理等",
      group: "其他",
    },
  ],
  dimensions: [
    {
      key: "material",
      label: "材料成本",
      group: "manufacturing",
      expectedRatioRange: [50, 90],
      agentId: "material_agent",
      description: "挂面纸/芯纸/中纸采购成本（复合纸板），含损耗；瓦楞纸板为成本主导（常占 70-90%）",
      order: 1,
    },
    {
      key: "labor",
      label: "人工成本",
      group: "manufacturing",
      expectedRatioRange: [5, 18],
      agentId: "labor_agent",
      description: "粘箱/钉箱、检验整理等人工工序，随生产地域浮动",
      order: 2,
    },
    {
      key: "process",
      label: "加工费（含设备）",
      group: "manufacturing",
      expectedRatioRange: [3, 30],
      agentId: "process_agent",
      description: "柔印、覆膜、模切等设备及油墨驱动工艺；素箱（柔印少色/无表面处理）占比偏低属正常",
      order: 3,
    },
    {
      key: "design_plate",
      label: "设计与制版成本",
      group: "commercial",
      expectedRatioRange: [3, 40],
      agentId: "design_agent",
      description: "设计费、制版、打样等",
      order: 5,
    },
    {
      key: "finance_other",
      label: "财务与其他成本",
      group: "commercial",
      expectedRatioRange: [5, 15],
      agentId: "finance_agent",
      description: "管理费用、物流、包装、税费、利润等",
      order: 6,
    },
  ],
};
