import type { ProductTypeConfig } from "@/types";

/**
 * 平面彩印产品类型配置（画册 / 海报 / 说明书等单张或多页平面印刷品）
 * 复用彩盒的 5 维度成本结构（材料/人工/加工费/设计制版/财务），
 * 仅字段与成本公式不同（派生量与各 Agent 按 productType=flat_print 分支）。
 *
 * 新增产品类型只需在此目录添加新配置文件并在 registry 中注册。
 */
export const flatPrintConfig: ProductTypeConfig = {
  code: "flat_print",
  name: "平面彩印",
  description: "画册、海报、说明书等单张/多页平面印刷品，含纸张、印色、装订等成本",
  steps: [
    {
      id: "upload",
      title: "上传资料",
      description: "上传设计稿或成品样图，帮助系统识别尺寸与工艺特征",
    },
    {
      id: "info",
      title: "补充信息",
      description: "填写印量、成品尺寸、页数、纸张、印色、装订等关键参数，信息越完整估算越准",
      fieldKeys: [
        "quantity",
        "length",
        "width",
        "pages",
        "material",
        "grammage",
        "coverGrammage",
        "printMethod",
        "colorCount",
        "spotColorCount",
        "surfaceTreatment",
        "binding",
        "provideReadyDesign",
        "deliveryLocation",
        "targetDelivery",
      ],
    },
    {
      id: "report",
      title: "成本报告",
      description: "查看多维度成本拆解与优化建议",
    },
  ],
  fields: [
    {
      key: "quantity",
      label: "印量",
      type: "number",
      required: true,
      weight: 15,
      impactHint: "印量直接影响纸张采购单价与开机成本分摊",
      placeholder: "如：5000",
      unit: "册",
      group: "订单信息",
    },
    {
      key: "length",
      label: "成品长度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "成品尺寸决定单张用纸面积",
      placeholder: "mm",
      unit: "mm",
      group: "成品尺寸",
    },
    {
      key: "width",
      label: "成品宽度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "成品尺寸决定单张用纸面积",
      placeholder: "mm",
      unit: "mm",
      group: "成品尺寸",
    },
    {
      key: "pages",
      label: "页数 (Pages)",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "页数决定总印张数与纸张用量（海报填 1）",
      placeholder: "如：32",
      unit: "P",
      defaultValue: 1,
      group: "成品尺寸",
    },
    {
      key: "material",
      label: "纸张类型",
      type: "select",
      required: true,
      weight: 12,
      impactHint: "纸张类型是材料成本的核心决定因素",
      group: "材料规格",
      options: [
        { value: "coated_paper", label: "铜版纸" },
        { value: "matte_paper", label: "哑粉纸" },
        { value: "offset_paper", label: "双胶纸" },
        { value: "photo_paper", label: "相纸" },
        { value: "pp_sheet", label: "PP纸" },
        { value: "special", label: "特种纸" },
      ],
    },
    {
      key: "grammage",
      label: "内页克重 / 整体克重",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "多页画册指内页用纸克重（随页数递减：≤32P→157g、60~100P→128g、104~200P→105g、204~300P→80g，可按需求覆盖）；单页/海报则为本张克重",
      group: "材料规格",
      options: [
        { value: "80", label: "80g" },
        { value: "105", label: "105g" },
        { value: "128", label: "128g" },
        { value: "157", label: "157g" },
        { value: "200", label: "200g" },
        { value: "230", label: "230g" },
        { value: "250", label: "250g" },
        { value: "300", label: "300g" },
      ],
      defaultValue: "157",
    },
    {
      key: "coverGrammage",
      label: "封面克重",
      type: "select",
      required: false,
      weight: 8,
      impactHint: "封面用纸克重，独立可选项；伊顿等客户常用 250g，可按客户需求调整，不影响内页克重",
      group: "材料规格",
      showWhen: { field: "binding", value: ["saddle", "perfect", "thread_sewn", "hardcover"] },
      options: [
        { value: "157", label: "157g" },
        { value: "200", label: "200g" },
        { value: "230", label: "230g" },
        { value: "250", label: "250g" },
        { value: "300", label: "300g" },
      ],
      defaultValue: "250",
    },
    {
      key: "printMethod",
      label: "印刷方式",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "印刷方式影响制版费与单位印刷成本",
      group: "印刷工艺",
      options: [
        { value: "offset", label: "胶印" },
        { value: "digital", label: "数码印刷" },
      ],
    },
    {
      key: "colorCount",
      label: "CMYK 印刷色数",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "CMYK 色数影响油墨成本与印刷难度",
      group: "印刷工艺",
      options: [
        { value: "1", label: "单色" },
        { value: "2", label: "双色" },
        { value: "3", label: "三色" },
        { value: "4", label: "四色 (CMYK)" },
      ],
    },
    {
      key: "spotColorCount",
      label: "专色色数 (Spot Color)",
      type: "number",
      required: false,
      weight: 4,
      impactHint: "专色需额外版费与调色/洗车费，显著提升成本",
      placeholder: "如：1",
      unit: "色",
      defaultValue: 0,
      group: "印刷工艺",
    },
    {
      key: "surfaceTreatment",
      label: "表面处理",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "表面处理工艺影响加工成本",
      group: "印刷工艺",
      options: [
        { value: "none", label: "无" },
        { value: "matte_laminate", label: "哑膜" },
        { value: "gloss_laminate", label: "亮膜" },
        { value: "varnish", label: "过油" },
        { value: "uv", label: "UV上光" },
        { value: "foil", label: "烫金/烫银" },
      ],
    },
    {
      key: "binding",
      label: "装订方式",
      type: "select",
      required: false,
      weight: 8,
      group: "后道工艺",
      options: [
        { value: "none", label: "散页/单张 (无装订)" },
        { value: "saddle", label: "骑马钉" },
        { value: "perfect", label: "无线胶装" },
        { value: "thread_sewn", label: "锁线胶装" },
        { value: "hardcover", label: "精装" },
        { value: "spiral", label: "圈装/YO圈" },
        { value: "accordion", label: "古线装/风琴折" },
        { value: "fold", label: "折页/对折页" },
      ],
      defaultValue: "none",
      impactHint: "装订为独立可选项，可与页数自由组合。注意可行性：骑马钉受厚度限制一般 ≤48P（纸越厚上限越低，157g内页约≤40P、80g内页可到~64P），超页数请改用无线胶装/锁线胶装。",
    },
    {
      key: "provideReadyDesign",
      label: "是否已提供完稿文件",
      type: "boolean",
      required: false,
      weight: 3,
      impactHint: "客户已提供可印刷完稿时，设计费减免为 0",
      group: "后道工艺",
      defaultValue: false,
    },
    {
      key: "deliveryLocation",
      label: "交付地点",
      type: "select",
      required: true,
      weight: 9,
      impactHint: "交付地点影响物流与人工地域系数",
      group: "交付信息",
      options: [
        { value: "east_china", label: "华东" },
        { value: "south_china", label: "华南" },
        { value: "north_china", label: "华北" },
        { value: "central_china", label: "华中" },
        { value: "southwest", label: "西南" },
        { value: "northeast", label: "东北" },
      ],
    },
    {
      key: "targetDelivery",
      label: "目标交期",
      type: "select",
      required: false,
      weight: 4,
      impactHint: "紧急交期可能产生加急费用",
      group: "交付信息",
      options: [
        { value: "standard", label: "标准 (15-20天)" },
        { value: "urgent", label: "加急 (7-10天)" },
        { value: "express", label: "特急 (3-5天)" },
      ],
      defaultValue: "standard",
    },
  ],
  dimensions: [
    {
      key: "material",
      label: "材料成本",
      group: "manufacturing",
      expectedRatioRange: [45, 65],
      agentId: "material_agent",
      description: "纸张采购成本（含损耗与油墨），随印张数与克重浮动",
      order: 1,
    },
    {
      key: "labor",
      label: "人工成本",
      group: "manufacturing",
      expectedRatioRange: [3, 12],
      agentId: "labor_agent",
      description: "装订等后道手工工序，随生产地域浮动",
      order: 2,
    },
    {
      key: "process",
      label: "加工费（含设备）",
      group: "manufacturing",
      expectedRatioRange: [12, 30],
      agentId: "process_agent",
      description: "印刷、覆膜、装订设备等工艺成本",
      order: 3,
    },
    {
      key: "design_plate",
      label: "设计与制版成本",
      group: "commercial",
      expectedRatioRange: [3, 40],
      agentId: "design_agent",
      description: "设计费、CTP制版、打样等",
      order: 5,
    },
    {
      key: "finance_other",
      label: "财务与其他成本",
      group: "commercial",
      expectedRatioRange: [5, 15],
      agentId: "finance_agent",
      description: "管理费用、物流、包装、税费、利润等",
      order: 6,
    },
  ],
};
