import type { ProductTypeConfig } from "@/types";

/**
 * 不干胶标签产品类型配置（标签 / 贴纸 / 不干胶）
 * 复用彩盒/平印的 5 维度成本结构（材料/人工/加工费/设计制版/财务），
 * 但与「平面彩印」同属平面策略家族：无盒型、无装订、无封面，
 * 按长×宽单张面积计（派生量走 flat_print 平面分支），
 * 材料/人工/加工/配方均复用 flat_print 那套（见 specialists.ts / seed-recipes.ts 的 label 分支）。
 *
 * 差异点（已刻意收敛，不另写算法）：
 *  - 无 pages / 无 coverGrammage / 无 binding（标签为单张/卷装，binding 恒为 none）；
 *  - 平面家族暂未计异形刀模/排废（标签实际有模切，属平面策略的已知简化，若需精确可升 C 级）。
 *
 * 新增产品类型只需在此目录添加新配置文件并在 registry 中注册。
 */
export const labelConfig: ProductTypeConfig = {
  code: "label",
  name: "不干胶标签",
  description: "不干胶标签/贴纸，单张或卷装，按长×宽面积计，无盒型、无装订",
  steps: [
    {
      id: "upload",
      title: "上传资料",
      description: "上传设计稿或成品样图，帮助系统识别尺寸与工艺特征",
    },
    {
      id: "info",
      title: "补充信息",
      description: "填写印量、成品尺寸、纸张、印色等关键参数，信息越完整估算越准",
      fieldKeys: [
        "quantity",
        "length",
        "width",
        "material",
        "grammage",
        "printMethod",
        "colorCount",
        "spotColorCount",
        "surfaceTreatment",
        "provideReadyDesign",
        "deliveryLocation",
        "targetDelivery",
      ],
    },
    {
      id: "report",
      title: "成本报告",
      description: "查看多维度成本拆解与优化建议",
    },
  ],
  fields: [
    {
      key: "quantity",
      label: "印量",
      type: "number",
      required: true,
      weight: 15,
      impactHint: "印量直接影响纸张采购单价与开机成本分摊",
      placeholder: "如：5000",
      unit: "枚",
      group: "订单信息",
    },
    {
      key: "length",
      label: "成品长度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "成品尺寸决定单张用纸面积",
      placeholder: "mm",
      unit: "mm",
      group: "成品尺寸",
    },
    {
      key: "width",
      label: "成品宽度",
      type: "number",
      required: true,
      weight: 10,
      impactHint: "成品尺寸决定单张用纸面积",
      placeholder: "mm",
      unit: "mm",
      group: "成品尺寸",
    },
    {
      key: "material",
      label: "面材类型",
      type: "select",
      required: true,
      weight: 12,
      impactHint: "面材类型是材料成本的核心决定因素",
      group: "材料规格",
      options: [
        { value: "coated_paper", label: "铜版纸" },
        { value: "matte_paper", label: "哑粉纸" },
        { value: "offset_paper", label: "双胶纸" },
        { value: "photo_paper", label: "相纸" },
        { value: "pp_sheet", label: "PP合成纸" },
        { value: "special", label: "特种纸" },
      ],
    },
    {
      key: "grammage",
      label: "面材克重",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "标签面材克重（随材质与厚度变化，可按需求覆盖）",
      group: "材料规格",
      options: [
        { value: "80", label: "80g" },
        { value: "105", label: "105g" },
        { value: "128", label: "128g" },
        { value: "157", label: "157g" },
        { value: "200", label: "200g" },
        { value: "230", label: "230g" },
        { value: "250", label: "250g" },
        { value: "300", label: "300g" },
      ],
      defaultValue: "80",
    },
    {
      key: "printMethod",
      label: "印刷方式",
      type: "select",
      required: true,
      weight: 10,
      impactHint: "印刷方式影响制版费与单位印刷成本",
      group: "印刷工艺",
      options: [
        { value: "offset", label: "胶印" },
        { value: "digital", label: "数码印刷" },
      ],
    },
    {
      key: "colorCount",
      label: "CMYK 印刷色数",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "CMYK 色数影响油墨成本与印刷难度",
      group: "印刷工艺",
      options: [
        { value: "1", label: "单色" },
        { value: "2", label: "双色" },
        { value: "3", label: "三色" },
        { value: "4", label: "四色 (CMYK)" },
      ],
    },
    {
      key: "spotColorCount",
      label: "专色色数 (Spot Color)",
      type: "number",
      required: false,
      weight: 4,
      impactHint: "专色需额外版费与调色/洗车费，显著提升成本",
      placeholder: "如：1",
      unit: "色",
      defaultValue: 0,
      group: "印刷工艺",
    },
    {
      key: "surfaceTreatment",
      label: "表面处理",
      type: "select",
      required: true,
      weight: 8,
      impactHint: "表面处理工艺影响加工成本（标签常用覆膜/过油/UV/烫金）",
      group: "印刷工艺",
      options: [
        { value: "none", label: "无" },
        { value: "matte_laminate", label: "哑膜" },
        { value: "gloss_laminate", label: "亮膜" },
        { value: "varnish", label: "过油" },
        { value: "uv", label: "UV上光" },
        { value: "foil", label: "烫金/烫银" },
      ],
    },
    {
      key: "provideReadyDesign",
      label: "是否已提供完稿文件",
      type: "boolean",
      required: false,
      weight: 3,
      impactHint: "客户已提供可印刷完稿时，设计费减免为 0",
      group: "后道工艺",
      defaultValue: false,
    },
    {
      key: "deliveryLocation",
      label: "交付地点",
      type: "select",
      required: true,
      weight: 9,
      impactHint: "交付地点影响物流与人工地域系数",
      group: "交付信息",
      options: [
        { value: "east_china", label: "华东" },
        { value: "south_china", label: "华南" },
        { value: "north_china", label: "华北" },
        { value: "central_china", label: "华中" },
        { value: "southwest", label: "西南" },
        { value: "northeast", label: "东北" },
      ],
    },
    {
      key: "targetDelivery",
      label: "目标交期",
      type: "select",
      required: false,
      weight: 4,
      impactHint: "紧急交期可能产生加急费用",
      group: "交付信息",
      options: [
        { value: "standard", label: "标准 (15-20天)" },
        { value: "urgent", label: "加急 (7-10天)" },
        { value: "express", label: "特急 (3-5天)" },
      ],
      defaultValue: "standard",
    },
  ],
  dimensions: [
    {
      key: "material",
      label: "材料成本",
      group: "manufacturing",
      expectedRatioRange: [45, 65],
      agentId: "material_agent",
      description: "面材采购成本（含损耗与油墨），随印张数与克重浮动",
      order: 1,
    },
    {
      key: "labor",
      label: "人工成本",
      group: "manufacturing",
      expectedRatioRange: [3, 12],
      agentId: "labor_agent",
      description: "后道手工工序，随生产地域浮动",
      order: 2,
    },
    {
      key: "process",
      label: "加工费（含设备）",
      group: "manufacturing",
      expectedRatioRange: [12, 30],
      agentId: "process_agent",
      description: "印刷、覆膜、装订设备等工艺成本",
      order: 3,
    },
    {
      key: "design_plate",
      label: "设计与制版成本",
      group: "commercial",
      expectedRatioRange: [3, 40],
      agentId: "design_agent",
      description: "设计费、CTP制版、打样等",
      order: 5,
    },
    {
      key: "finance_other",
      label: "财务与其他成本",
      group: "commercial",
      expectedRatioRange: [5, 15],
      agentId: "finance_agent",
      description: "管理费用、物流、包装、税费、利润等",
      order: 6,
    },
  ],
};
